services:
  - type: web
    name: ai-chatbot-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
